# Generated by Django 3.2.20 on 2023-07-14 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('focus_lesson', models.TextField()),
                ('lesson_date', models.DateTimeField()),
                ('terms_checked', models.BooleanField(default=False)),
                ('no_participants', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)])),
                ('level_ekipage', models.CharField(choices=[('Lätt C', 'Lätt C'), ('Lätt B', 'Lätt B'), ('Lätt A', 'Lätt A'), ('MSV C', 'MSV C'), ('MSV B', 'MSV B'), ('MSV A', 'MSV A'), ('Grand Prix', 'Grand Prix')], max_length=20)),
                ('booking_status', models.IntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Confirmed')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-lesson_date'],
            },
        ),
    ]
