# Generated by Django 3.2.20 on 2023-07-14 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonbooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='lessonbooking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
