# Generated by Django 3.2.20 on 2023-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_lessonbooking_lesson_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonbooking',
            options={'ordering': ['lesson_date']},
        ),
        migrations.AlterField(
            model_name='lessonbooking',
            name='lesson_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lessonbooking',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
